name: Pre Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write
      actions: write

    strategy:
      matrix:
        python_version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        hatch env create
    - name: Lint and typecheck
      run: |
        hatch run lint-check
    - name: Test
      run: |
        hatch run test

  pre-release:
    runs-on: windows-latest
    environment: release
    needs: test
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch pyinstaller
        hatch env create

    - name: Extract version
      id: extract_version
      shell: bash
      run: |
        VERSION=$(grep -oP '__version__\s*=\s*"\K[^"]+' imxCli/__init__.py)
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Fetch latest release version
      shell: bash
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name | sed 's/^v//')
        echo "latest_version=$LATEST_VERSION" >> $GITHUB_ENV

    - name: Check version match
      shell: bash
      run: |
        if [ "${{ env.version }}" = "${{ env.latest_version }}" ]; then
          echo "match=true" >> $GITHUB_ENV
        else
          echo "match=false" >> $GITHUB_ENV
        fi

    - name: Build exe
      run: python build-cli-app.py
      if: env.match == 'false'

    - name: Upload release
      if: env.match == 'false'
      uses: ncipollo/release-action@v1.16.0
      with:
        draft: true
        name: 🚀 Version ${{ env.version }}
        tag: v${{ env.version }}
        generateReleaseNotes: true
        artifacts: dist/imxCli-${{ env.version }}-windows.exe
        token: ${{ secrets.GITHUB_TOKEN }}
